# Change these first
owner: kuggar-anthony # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kuggar API
    url: https://api.kuggar.io/index.html
  - name: Customer Portal
    url: https://portal.kuggar.io/index.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kuggar.io
  # baseUrl: /your-repo-name
  logoUrl: https://kugg.ar/images/kuggar-icon.svg
  name: Kuggar Status
  introTitle: "**Kuggar** Virtual Cards Platform Uptime"
  introMessage: This is a status page which shows the status of different components and cloud instances of the Kuggar Virtual Cards Platform, as well as the status of platforms of different virtual card issuers and other third parties that Kuggar integrates into (where possible).
  navbar:
    - title: Status
      href: /
    - title: Kuggar
      href: https://kugg.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
