# Change these first
owner: kuggar-anthony # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kuggar API
    url: https://api.kuggar.io/api/v2/ping
    expectedStatusCodes:
      - 204
    icon: https://kugg.ar/favicon.ico
  - name: Kuggar API - Azure (Australia East)
    url: https://kuggar-prod-au-api.azurewebsites.net/api/v2/ping
    expectedStatusCodes:
      - 204
    icon: https://kugg.ar/favicon.ico
  - name: Kuggar API - AWS (Sydney)
    url: http://kuggarprodauapiv2-env.eba-yzpksewj.ap-southeast-2.elasticbeanstalk.com/api/v2/ping
    expectedStatusCodes:
      - 204
    icon: https://kugg.ar/favicon.ico
  - name: Customer Portal
    url: https://portal.kuggar.io/index.html
    icon: https://kugg.ar/favicon.ico
  - name: Customer Portal - Azure (Australia East)
    url: https://ambitious-bush-0f1487400.1.azurestaticapps.net/index.html
    icon: https://kugg.ar/favicon.ico
  - name: Customer Portal - AWS (Sydney)
    url: http://kuggar-prod-web-cp.s3-website-ap-southeast-2.amazonaws.com/index.html
    icon: https://kugg.ar/favicon.ico
  - name: MongoDB Atlas - Azure (Australia East)
    check: "tcp-ping"
    url: platform-shard-00-00.sdr9y.mongodb.net
    port: 27017
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
  - name: MongoDB Atlas - AWS (Sydney)
    check: "tcp-ping"
    url: platform-shard-00-01.sdr9y.mongodb.net
    port: 27017
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
  - name: MongoDB Atlas - Azure (UK South)
    check: "tcp-ping"
    url: platform-shard-00-02.sdr9y.mongodb.net
    port: 27017
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
  - name: MongoDB Atlas - Azure (UAE North)
    check: "tcp-ping"
    url: platform-shard-00-03.sdr9y.mongodb.net
    port: 27017
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
  - name: MongoDB Atlas - AWS (London)
    check: "tcp-ping"
    url: platform-shard-00-04.sdr9y.mongodb.net
    port: 27017
    icon: https://www.mongodb.com/assets/images/global/favicon.ico
  - name: Fixer.io (Foreign Exchange API)
    url: https://data.fixer.io/api/
    icon: https://fixer.io/fixer_images/fixer_ico.png

status-website:
  cname: status.kuggar.io
  themeUrl: https://cdn.statically.io/gh/kuggar-anthony/upptime/master/assets/custom-theme.css
  logoUrl: https://kugg.ar/images/kuggar-icon.svg
  favicon: https://kugg.ar/favicon.ico
  faviconSvg: https://kugg.ar/images/kuggar-icon.svg
  name: Kuggar Status
  introTitle: "**<span style=\"color:#0046ad\">Ku<span style=\"color:#fd3c39\">g</span>gar</span>** Virtual Cards Platform Uptime"
  introMessage: This is a status page which shows the status of different components and cloud instances of the Kuggar Virtual Cards Platform, as well as the status of platforms of different virtual card issuers and other third parties that Kuggar integrates into (where possible).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://kugg.ar

i18n:
  footer: "[Kuggar Pty Ltd](https://kugg.ar)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
