# Change these first
owner: kuggar-anthony # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kuggar API
    url: "$API_KUGGAR"
    icon: https://kugg.ar/favicon.ico
  - name: Kuggar API - Azure (Australia East)
    url: "$API_KUGGAR_AZURE_AU"
    icon: https://kugg.ar/favicon.ico
  - name: Kuggar API - AWS (Sydney)
    url: "$API_KUGGAR_AWS_AU"
    icon: https://kugg.ar/favicon.ico
  - name: Customer Portal
    url: "$CUSTOMER_PORTAL"
  - name: Customer Portal - Azure (Australia East)
    url: "$CUSTOMER_PORTAL_AZURE_AU"
  - name: Customer Portal - AWS (Sydney)
    url: "$CUSTOMER_PORTAL_AWS_AU"

status-website:
  cname: status.kuggar.io
  logoUrl: https://kugg.ar/images/kuggar-icon.svg
  favicon: https://kugg.ar/favicon.ico
  faviconSvg: https://kugg.ar/images/kuggar-icon.svg
  name: Kuggar Status
  introTitle: "**Kuggar** Virtual Cards Platform Uptime"
  introMessage: This is a status page which shows the status of different components and cloud instances of the Kuggar Virtual Cards Platform, as well as the status of platforms of different virtual card issuers and other third parties that Kuggar integrates into (where possible).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://kugg.ar

i18n:
  footer: "[Kuggar Pty Ltd](https://kugg.ar)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
